Corpus:
  path: /home/beiming/RAW_DATA/MEG/case0554_A2_220715/Sentences
  label_file: PB400_phone.txt            

Data_setup:
  session: Baseline # Baseline, Imagination, Articulation, Perception
  experiment_type: Cross-validation
  CV_num: 8
  CV_to_run: [0] # [0, 1, 2, 3, 4, 5, 6, 7, 8]
  train_ratio: 0.9
   
MEG_data:
  fix_missing_values: False
  sampling_rate: 1000 # in Hz
  dim_selection: False
  max_dim: 204
  dim_selection: True
  selected_dims: [0, 30, 40, 60] # Range of selected sensors [start1, end1, start2, end2, ... ]
  low_pass_filtering: False
  LP_cutoff_freq: 400 # in Hz (half of sampling_rate at most < 500Hz)
  framing: True
  frame_len: 10 # 25ms ~ 50 ms
  frame_shift: 10 # 10 ms
  drop_last: True
  windowing: True # to be implemented
  window_function: hamming # hamming or hanning is good
  delta: False # to be added
      
Transforms:
  normalize_input: True
  
# Deep learning model setup
  
NN_setup:
  n_cnn_layers: 2
  n_rnn_layers: 2
  rnn_dim: 256
  stride: 2
  dropout: 0.3
  
Training setup:
  learning_rate: 0.0005 #1e-4
  batch_size: 1
  epochs: 10
  early_stop: True
  patient: 10
  
Testing_setup:
  save_model: True
  decoding: Greedy
#  beam_size: 2
  
## Data augmentations
  
data_augmentation:
  random_sin_noise_inj: True
  random_rotate: False
  random_noise: False
  random_time_mask: False
  random_freq_mask: False
  
random_sin_noise_inj:
  ratio: 0.5
  noise_energy_ratio: 0.05
  noise_freq: 20
  fs: 100
  
random_time_mask:
  ratio: 0.8
  mask_num: 50
  
random_freq_mask:
  ratio: 0.8
  mask_num: 20
    
random_rotate:
  ratio: 0.8
  r_min: -10
  r_max: 10
  
random_noise:
  ratio: 0.7
  r_min: -30
  r_max: 30
